package com.example.allhome.data.DAO

import androidx.lifecycle.LiveData
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.example.allhome.data.entities.GroceryItemEntity
import com.example.allhome.data.entities.GroceryListEntity
import com.example.allhome.data.entities.GroceryListWithItemCount
import com.example.allhome.data.relations.GroceryListAndGroceryItems
import com.example.allhome.data.relations.GroceryListAndGroceryItemsName
import com.example.allhome.data.relations.GroceryListAndGroceryItemsName1

@Dao
interface GroceryListDAO {
    @Insert
    fun addItem(groceryListEntity: GroceryListEntity):Long
    @Query("SELECT * FROM grocery_lists")
    fun readAllGroceryItem(): LiveData<List<GroceryListEntity>>

    @Query("SELECT *,(SELECT COUNT(*) FROM grocery_items WHERE grocery_list_unique_id =grocery_lists.auto_generated_unique_id ) as grocery_item_count FROM grocery_lists")
    fun readGroceryListWithItem():List<GroceryListAndGroceryItems>

    @Query("SELECT *,(SELECT COUNT(*) FROM grocery_items WHERE grocery_list_unique_id =grocery_lists.auto_generated_unique_id ) AS itemCount,(SELECT COUNT(*) FROM grocery_items WHERE grocery_list_unique_id =grocery_lists.auto_generated_unique_id AND bought= 1 ) AS itemBought FROM grocery_lists")
    fun selectGroceryListWithItemCount():List<GroceryListWithItemCount>

    @Query("SELECT * FROM grocery_lists WHERE auto_generated_unique_id =:autoGeneratedUniqueId LIMIT 1")
    fun getGroceryList(autoGeneratedUniqueId:String): LiveData<GroceryListEntity>

}