package com.example.allhome.grocerylist

import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.view.ViewTreeObserver.OnScrollChangedListener
import android.widget.Button
import android.widget.LinearLayout
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProvider
import androidx.recyclerview.widget.RecyclerView
import com.example.allhome.R
import com.example.allhome.data.AllHomeDatabase
import com.example.allhome.data.entities.GroceryListEntity
import com.example.allhome.data.entities.GroceryListWithItemCount
import com.example.allhome.databinding.FragmentGroceryListBinding
import com.example.allhome.databinding.GroceryListItemBinding
import com.example.allhome.grocerylist.viewmodel.GroceryListFragmentViewModel
import com.google.android.material.textfield.TextInputEditText
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Dispatchers.Main
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.text.SimpleDateFormat
import java.util.*


class GroceryListFragment : Fragment() {
    private lateinit var mDataBindingUtil:FragmentGroceryListBinding
    private lateinit var mGroceryListFragmentViewModel: GroceryListFragmentViewModel;

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {

        mGroceryListFragmentViewModel = ViewModelProvider(this).get(GroceryListFragmentViewModel::class.java)
        mDataBindingUtil = DataBindingUtil.inflate(inflater, R.layout.fragment_grocery_list, container, false)
        mDataBindingUtil.apply {

        }

        val groceryListRecyclerViewAdapter = GroceryListRecyclerViewAdapter(requireContext())
        mDataBindingUtil.groceryListRecyclerview.adapter = groceryListRecyclerViewAdapter

        CoroutineScope(Dispatchers.IO).launch {
            mGroceryListFragmentViewModel.getGroceryLists(requireContext())
            withContext(Main) {
                groceryListRecyclerViewAdapter.mGroceryListWithItemCount = mGroceryListFragmentViewModel.groceryList
                groceryListRecyclerViewAdapter.notifyDataSetChanged()

            }

        }
        mDataBindingUtil.groceryListRecyclerview.addOnScrollListener(object: RecyclerView.OnScrollListener() {
            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
                if (dy > 0 ||dy<0 && mDataBindingUtil.fab.isShown())
                {
                    mDataBindingUtil.fab.hide();
                }
                super.onScrolled(recyclerView, dx, dy)
            }

            override fun onScrollStateChanged(recyclerView: RecyclerView, newState: Int) {
                if (newState == RecyclerView.SCROLL_STATE_IDLE)
                {
                    mDataBindingUtil.fab.show();
                }
                super.onScrollStateChanged(recyclerView, newState)
            }

        })

       /* mDataBindingUtil.groceryListRecyclerview.addOnScrollListener(OnScrollChangedListener {

        })*/

        mDataBindingUtil.fab.setOnClickListener{
            showGroceryListNameInput()
        }
        return mDataBindingUtil.root
    }
    private fun showGroceryListNameInput(){
        val groceryListNameInputDialog = CustomDialog(requireContext())
        groceryListNameInputDialog.setButtonClickListener(View.OnClickListener {
            var groceryListName = groceryListNameInputDialog.groceryListName()

            if (groceryListName.isEmpty()) {
                Toast.makeText(requireContext(), "Please provide name", Toast.LENGTH_SHORT).show()
                return@OnClickListener
            }

            var uniqueID = UUID.randomUUID().toString()
            val simpleDateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
            simpleDateFormat.timeZone = TimeZone.getTimeZone("GMT")
            val datetimeCreated: String = simpleDateFormat.format(Date())
            val groceryListEntity = GroceryListEntity(autoGeneratedUniqueId = uniqueID, name = groceryListName, datetimeCreated = datetimeCreated, shoppingDatetime = "0000-00-00 00:00:00");
            CoroutineScope(Dispatchers.IO).launch {
                AllHomeDatabase.getDatabase(requireContext()).groceryListDAO().addItem(groceryListEntity)
                withContext(Dispatchers.Main) {
                    groceryListNameInputDialog.mAlertDialog.dismiss()
                    val intent = Intent(requireContext(), SingleGroceryListActivity::class.java)
                    intent.putExtra(AddGroceryListItemActivity.GROCERY_LIST_UNIQUE_ID_EXTRA_DATA_TAG, uniqueID)
                    startActivity(intent)
                }
            }

            if (true) {

                return@OnClickListener
            }


        })
        groceryListNameInputDialog.createPositiveButton("Continue")
        groceryListNameInputDialog.show()
    }

    /**
     * Custom alertdialog
     */
    class CustomDialog(context: Context) : AlertDialog.Builder(context) {
        companion object{
            var POSITIVE_BUTTON_ID = AlertDialog.BUTTON_POSITIVE
        }
        var mGroceryListNameInput: LinearLayout;
        lateinit var mOnClickListener: View.OnClickListener;
        lateinit var mAlertDialog: AlertDialog;
        init {

            mGroceryListNameInput = LayoutInflater.from(context).inflate(R.layout.grocery_list_name_input, null, false) as LinearLayout
            this.setView(mGroceryListNameInput)
        }

        fun setButtonClickListener(onClickListener: View.OnClickListener) {
            mOnClickListener = onClickListener
        }
        fun createPositiveButton(buttonLabel: String){
            this.setPositiveButton(buttonLabel, null)
        }
        fun groceryListName():String{
            var groceryListNameTextInput: TextInputEditText = mGroceryListNameInput.findViewById(R.id.grocery_list_name_textinputedittext)
            return groceryListNameTextInput.text.toString();

        }

        override fun show(): AlertDialog {

            mAlertDialog = super.show()
            val positiveBtn: Button = mAlertDialog.getButton(AlertDialog.BUTTON_POSITIVE)

            if(mOnClickListener != null){
                if(positiveBtn !=null){
                    positiveBtn.id = POSITIVE_BUTTON_ID
                    positiveBtn.setOnClickListener(mOnClickListener)
                }


            }

            return mAlertDialog
        }
    }

}

/**
 *
 */
class GroceryListRecyclerViewAdapter(val contextParams: Context) : RecyclerView.Adapter<GroceryListRecyclerViewAdapter.ItemViewHolder>() {
    var mGroceryListWithItemCount: List<GroceryListWithItemCount> = arrayListOf()

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ItemViewHolder {

        val layoutInflater = LayoutInflater.from(parent.context)

        val groceryListItemBinding = GroceryListItemBinding.inflate(layoutInflater, parent, false)
        val itemViewHolder = ItemViewHolder(groceryListItemBinding)

        return itemViewHolder;

    }

    override fun onBindViewHolder(holder: ItemViewHolder, position: Int) {

        val groceryItemEntity = mGroceryListWithItemCount[position]
        holder.groceryListItemBinding.groceryListWithCount= groceryItemEntity
        holder.groceryListItemBinding.executePendingBindings()
    }

    override fun getItemCount(): Int {
        return mGroceryListWithItemCount.size
    }

    inner class ItemViewHolder(var groceryListItemBinding: GroceryListItemBinding) : RecyclerView.ViewHolder(groceryListItemBinding.root), View.OnClickListener {

        init{
            groceryListItemBinding.root.setOnClickListener(this)
        }
        override fun onClick(v: View?) {

            val groceryListWithCount  = groceryListItemBinding.groceryListWithCount
            val intent = Intent(contextParams, SingleGroceryListActivity::class.java)
            intent.putExtra(AddGroceryListItemActivity.GROCERY_LIST_UNIQUE_ID_EXTRA_DATA_TAG, groceryListWithCount?.groceryListEntity?.autoGeneratedUniqueId)
            contextParams.startActivity(intent)

        }

    }


}
