package com.example.allhome.grocerylist

import android.annotation.SuppressLint
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.util.Log
import android.view.Menu
import android.view.MenuItem
import android.view.View
import android.view.animation.Animation
import android.view.animation.ScaleAnimation
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.cardview.widget.CardView
import androidx.databinding.DataBindingUtil
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProvider
import androidx.recyclerview.widget.DividerItemDecoration
import androidx.recyclerview.widget.ItemTouchHelper
import androidx.recyclerview.widget.RecyclerView
import androidx.recyclerview.widget.RecyclerView.OnScrollListener
import com.example.allhome.R
import com.example.allhome.data.entities.GroceryItemEntity
import com.example.allhome.databinding.ActivitySingleGroceryListBinding
import com.example.allhome.grocerylist.viewmodel.GroceryListViewModel
import com.example.allhome.grocerylist.viewmodel_factory.GroceryListViewModelFactory
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers.IO
import kotlinx.coroutines.Dispatchers.Main
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.*


class SingleGroceryListActivity : AppCompatActivity() {

    lateinit var mGroceryListViewModel: GroceryListViewModel;
    lateinit var dataBindingUtil: ActivitySingleGroceryListBinding
    lateinit var mItemTouchHelper: ItemTouchHelper;
    var groceryListUniqueId: String = "d6c2db66-4ea1-4b21-9278-d094b09a2f99"

    companion object {
        val ADD_ITEM_REQUEST = 1;
        val UPDATE_ITEM_REQUEST = 2;
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_single_grocery_list)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)

        // create AddGroceryListItemActivityViewModel using AddGroceryListItemActivityViewModelFactory
        val addGroceryListItemActivityViewModelFactory = GroceryListViewModelFactory(null, null)
        mGroceryListViewModel = ViewModelProvider(this, addGroceryListItemActivityViewModelFactory).get(
                GroceryListViewModel::class.java
        )


        //Bind data
        dataBindingUtil = DataBindingUtil.setContentView<ActivitySingleGroceryListBinding>(this, R.layout.activity_single_grocery_list
        ).apply {
            this.lifecycleOwner = this@SingleGroceryListActivity
            this.groceryListViewModel = mGroceryListViewModel


        }

        val groceryItemRecyclerViewAdapter = GroceryItemRecyclerViewAdapter(this)

        dataBindingUtil.groceryItemRecyclerview.adapter = groceryItemRecyclerViewAdapter
        mGroceryListViewModel.setSelectedGroceryList(this, groceryListUniqueId).observe(this,
                Observer {
                    supportActionBar?.title = mGroceryListViewModel.selectedGroceryList.value?.name;
                })

        mGroceryListViewModel.sortingAndGrouping.observe(this, Observer {
            when(it){
                GroceryListViewModel.SORT_ALPHABETICALLY->{
                    mGroceryListViewModel.sortAlpahetically(mGroceryListViewModel.toBuyGroceryItems,mGroceryListViewModel.boughtGroceryItems)
                    mGroceryListViewModel.mergeToBuyAndBoughtItems(mGroceryListViewModel.toBuyGroceryItems,mGroceryListViewModel.boughtGroceryItems)
                    dataBindingUtil.groceryItemRecyclerview.adapter?.notifyDataSetChanged()
                }
                GroceryListViewModel.GROUP_BY_CATEGORY->{
                    mGroceryListViewModel.groupByCategory()
                    dataBindingUtil.groceryItemRecyclerview.adapter?.notifyDataSetChanged()
                }
            }
        })

        if (mGroceryListViewModel.selectedGroceryListEntity == null) {

            CoroutineScope(IO).launch {
                mGroceryListViewModel.setSelectedGroceryList(this@SingleGroceryListActivity, groceryListUniqueId
                )
                withContext(Main) {
                    //supportActionBar?.title = mGroceryListViewModel.selectedGroceryList?.name;
                    //Log.e("SELECTED ",mGroceryListViewModel.selectedGroceryList?.autoGeneratedUniqueId+" aa")

                }

            }
        }
        if (mGroceryListViewModel.selectedGroceryListItemList.isNullOrEmpty()) {

            CoroutineScope(IO).launch {
                val groceryItemEntities = mGroceryListViewModel.getGroceryItems(this@SingleGroceryListActivity, groceryListUniqueId)

                withContext(Main) {

                    groceryItemRecyclerViewAdapter.mGroceryItems = groceryItemEntities
                    groceryItemRecyclerViewAdapter.notifyDataSetChanged()
                }
            }
        } else {
            groceryItemRecyclerViewAdapter.mGroceryItems = mGroceryListViewModel.selectedGroceryListItemList
            groceryItemRecyclerViewAdapter.notifyDataSetChanged()
        }



        dataBindingUtil.fab.setOnClickListener(View.OnClickListener {
            val intent = Intent(this, AddGroceryListItemActivity::class.java)
            intent.putExtra(AddGroceryListItemActivity.GROCERY_LIST_UNIQUE_ID_EXTRA_DATA_TAG, groceryListUniqueId)
            startActivityForResult(intent, ADD_ITEM_REQUEST)

        })


        mItemTouchHelper = ItemTouchHelper(object : ItemTouchHelper.SimpleCallback(ItemTouchHelper.UP or ItemTouchHelper.DOWN, 0) {

            override fun getMovementFlags(recyclerView: RecyclerView, viewHolder: RecyclerView.ViewHolder): Int {

                val itemViewHolder: GroceryItemRecyclerViewAdapter.ItemViewHolder = viewHolder as GroceryItemRecyclerViewAdapter.ItemViewHolder
                val groceryItemEntity = itemViewHolder.groceryListItemBinding.groceryItemEntity

                if (groceryItemEntity!!.bought == 1 || groceryItemEntity.forCategoryDivider) {
                    return ItemTouchHelper.Callback.makeMovementFlags(
                            0,
                            0
                    )
                }
                val dragFlags = if (groceryItemRecyclerViewAdapter.mDraggable) ItemTouchHelper.UP or ItemTouchHelper.DOWN else 0
                return ItemTouchHelper.Callback.makeMovementFlags(
                        dragFlags,
                        0
                )
            }

            override fun isLongPressDragEnabled(): Boolean {
                return true
            }

            override fun onMove(recyclerView: RecyclerView, viewHolder: RecyclerView.ViewHolder, target: RecyclerView.ViewHolder): Boolean {

                val sourcePosition = viewHolder.adapterPosition
                val targetPosition = target.adapterPosition

                if(mGroceryListViewModel.sortingAndGrouping.value == GroceryListViewModel.SORT_ALPHABETICALLY){
                    if (mGroceryListViewModel.toBuyGroceryItems.size - 1 >= targetPosition) {
                        Collections.swap(groceryItemRecyclerViewAdapter.mGroceryItems, sourcePosition, targetPosition)
                        groceryItemRecyclerViewAdapter?.notifyItemMoved(sourcePosition, targetPosition)

                        return true
                    }
                }else{
                    val itemViewHolderSource: GroceryItemRecyclerViewAdapter.ItemViewHolder = viewHolder as GroceryItemRecyclerViewAdapter.ItemViewHolder
                    val itemViewHolderTarget: GroceryItemRecyclerViewAdapter.ItemViewHolder = target as GroceryItemRecyclerViewAdapter.ItemViewHolder

                    val sourceGroceryItemEntity = itemViewHolderSource.groceryListItemBinding.groceryItemEntity
                    var targetGroceryItemEntity = itemViewHolderTarget.groceryListItemBinding.groceryItemEntity

                      if(targetGroceryItemEntity!!.forCategoryDivider ||!sourceGroceryItemEntity!!.category.equals(targetGroceryItemEntity!!.category)
                              || targetGroceryItemEntity.bought == 1){
                        return false
                        }
                    Collections.swap(groceryItemRecyclerViewAdapter.mGroceryItems, sourcePosition, targetPosition)
                    groceryItemRecyclerViewAdapter?.notifyItemMoved(sourcePosition, targetPosition)
                    return true
                }


                return false

            }

            @SuppressLint("ResourceAsColor")
            override fun clearView(recyclerView: RecyclerView, viewHolder: RecyclerView.ViewHolder) {
                super.clearView(recyclerView, viewHolder)

                groceryItemRecyclerViewAdapter?.itemDroped()

                mGroceryListViewModel.selectedGroceryListItemList = groceryItemRecyclerViewAdapter.mGroceryItems as ArrayList<GroceryItemEntity>

                /*val attrs = intArrayOf(R.attr.selectableItemBackground)
                val typedArray = this@SingleGroceryListActivity.obtainStyledAttributes(attrs)
                val backgroundResource = typedArray.getResourceId(0, 0)

                val itemViewHolder: GroceryItemRecyclerViewAdapter.ItemViewHolder = viewHolder as GroceryItemRecyclerViewAdapter.ItemViewHolder
                itemViewHolder.groceryListItemBinding.groceryItemParentLayout.setBackgroundColor(backgroundResource)
                typedArray.recycle()*/

            }

            override fun onSelectedChanged(viewHolder: RecyclerView.ViewHolder?, actionState: Int) {
                super.onSelectedChanged(viewHolder, actionState)
                if (actionState == ItemTouchHelper.ACTION_STATE_DRAG) {

                    val itemViewHolder: GroceryItemRecyclerViewAdapter.ItemViewHolder = viewHolder as GroceryItemRecyclerViewAdapter.ItemViewHolder

                    //val cardView:CardView = itemViewHolder.groceryListItemBinding.groceryItemParentLayout

                }
            }

            override fun onSwiped(viewHolder: RecyclerView.ViewHolder, direction: Int) {
                TODO("Not yet implemented")
            }

        })
        mItemTouchHelper?.attachToRecyclerView(dataBindingUtil.groceryItemRecyclerview)
        groceryItemRecyclerViewAdapter.mTouchHelper = mItemTouchHelper
    }


    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)

        if (requestCode == ADD_ITEM_REQUEST && resultCode == RESULT_OK) {

            CoroutineScope(IO).launch {

                val groceryItemEntity = mGroceryListViewModel.getGroceryListItem(this@SingleGroceryListActivity, groceryListUniqueId)
                withContext(Main) {

                    val indexOfNewItem = mGroceryListViewModel.addGroceryListItemToBuy(mGroceryListViewModel.toBuyGroceryItems, mGroceryListViewModel.boughtGroceryItems, groceryItemEntity)
                    val scrollListener = object : OnScrollListener() {
                        var found = false
                        override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
                            val viewHolder = dataBindingUtil.groceryItemRecyclerview.findViewHolderForAdapterPosition(
                                    indexOfNewItem
                            )
                            if (viewHolder != null && !found) {
                                val fadeInAnimation = ScaleAnimation(0f, 1f, 0f, 1f, Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f)
                                fadeInAnimation.duration = 500
                                fadeInAnimation.fillAfter = true
                                val itemViewHolder: GroceryItemRecyclerViewAdapter.ItemViewHolder = viewHolder as GroceryItemRecyclerViewAdapter.ItemViewHolder
                                itemViewHolder.groceryListItemBinding.groceryItemParentLayout.startAnimation(fadeInAnimation)

                                dataBindingUtil.groceryItemRecyclerview.removeOnScrollListener(this)
                                found = true
                            }


                        }
                    }
                    dataBindingUtil.groceryItemRecyclerview.addOnScrollListener(scrollListener)
                    dataBindingUtil.groceryItemRecyclerview.adapter?.notifyItemInserted(indexOfNewItem)
                    dataBindingUtil.groceryItemRecyclerview.scrollToPosition(indexOfNewItem)

                }

            }
        } else if (requestCode == UPDATE_ITEM_REQUEST && resultCode == RESULT_OK) {
            Toast.makeText(this, "Updated", Toast.LENGTH_SHORT).show()

            val updatedGroceryListId = data?.getIntExtra(
                    AddGroceryListItemActivity.GROCERY_LIST_ITEM_ID_EXTRA_DATA_TAG,
                    -1
            )
            val itemIndex = data?.getIntExtra(
                    AddGroceryListItemActivity.GROCERY_LIST_ITEM_INDEX_EXTRA_DATA_TAG,
                    -1
            )

            CoroutineScope(IO).launch {
                val groceryItemEntity = mGroceryListViewModel.getGroceryListItem(
                        this@SingleGroceryListActivity,
                        updatedGroceryListId!!,
                        groceryListUniqueId
                )
                mGroceryListViewModel.selectedGroceryListItemList.set(
                        itemIndex!!,
                        groceryItemEntity!!
                )
                withContext(Main) {

                    val viewHolder = dataBindingUtil.groceryItemRecyclerview.findViewHolderForLayoutPosition(
                            itemIndex!!
                    )
                    viewHolder?.itemView?.setBackgroundColor(Color.RED)

                    dataBindingUtil.groceryItemRecyclerview.adapter?.notifyItemChanged(itemIndex)
                    dataBindingUtil.groceryItemRecyclerview.adapter?.notifyItemRangeChanged(
                            itemIndex,
                            mGroceryListViewModel.selectedGroceryListItemList.size
                    )
                }
            }


            /*val viewHolder = dataBindingUtil.groceryItemRecyclerview.findViewHolderForLayoutPosition(itemIndex!!)
            viewHolder?.itemView?.setBackgroundColor(Color.RED)

            dataBindingUtil.groceryItemRecyclerview.adapter?.notifyItemChanged(itemIndex)
            dataBindingUtil.groceryItemRecyclerview.adapter?.notifyItemRangeChanged(itemIndex,mGroceryListViewModel.selectedGroceryListItemList.size)*/

            /*mGroceryListViewModel.selectedGroceryItem.observe(this, Observer {
                mGroceryListViewModel.selectedGroceryListItemList.set(itemIndex!!, it)
                val viewHolder = dataBindingUtil.groceryItemRecyclerview.findViewHolderForLayoutPosition(itemIndex)
                viewHolder?.itemView?.setBackgroundColor(Color.RED)


                dataBindingUtil.groceryItemRecyclerview.adapter?.notifyItemChanged(itemIndex)
                dataBindingUtil.groceryItemRecyclerview.adapter?.notifyItemRangeChanged(itemIndex,mGroceryListViewModel.selectedGroceryListItemList.size)
            })

            updatedGroceryListId?.let {
                Log.e("data","updated 123 "+it)
               mGroceryListViewModel.getGroceryListItem(this@SingleGroceryListActivity, it,groceryListUniqueId)

            }*/

        } else {
            Toast.makeText(this, "OTHER", Toast.LENGTH_SHORT).show()
        }
    }

    override fun onCreateOptionsMenu(menu: Menu?): Boolean {
        menuInflater.inflate(R.menu.single_grocery_item_menu, menu)
        return true
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        when(item.itemId){
            R.id.menu_group_by_category->{
                mGroceryListViewModel.sortingAndGrouping.value = GroceryListViewModel.GROUP_BY_CATEGORY
            }
            R.id.menu_sort_alphabetically->{
                mGroceryListViewModel.sortingAndGrouping.value = GroceryListViewModel.SORT_ALPHABETICALLY
            }
        }

        return true
    }
}