package com.example.allhome.data.entities

import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize
import java.io.Serializable


@Parcelize
@Entity(tableName = "grocery_lists")
data class GroceryListEntity(
        @PrimaryKey(autoGenerate = false)
        @ColumnInfo(name = "auto_generated_unique_id",index = true) var autoGeneratedUniqueId:String,
        @ColumnInfo(name = "name") var name:String,
        @ColumnInfo(name = "datetime_created",defaultValue = "CURRENT_TIMESTAMP") var datetimeCreated:String,
        @ColumnInfo(name = "shopping_datetime") var shoppingDatetime:String,
        @ColumnInfo(name = "location") var location:String,
        @ColumnInfo(name = "longitude") var longitude:Double,
        @ColumnInfo(name = "latitude") var latitude:Double,
        @ColumnInfo(name = "viewing_type",defaultValue="0") var viewingType:Int
)

@Parcelize
data class GroceryListWithItemCount(
    @Embedded val groceryListEntity: GroceryListEntity,
    val itemCount:Int,
    val itemBought:Int
)




