package com.example.allhome.data.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "todos")
data class TodosEntity(
    @PrimaryKey(autoGenerate = false)
    @ColumnInfo(name = "auto_generated_unique_id",index = true) var autoGeneratedUniqueId:String,
    @ColumnInfo(name = "name") var name:String,
    @ColumnInfo(name = "due_date",defaultValue="0") var dueDate:Int,
    @ColumnInfo(name = "repeat_until",defaultValue="0") var repeatUntil:Int,
    @ColumnInfo(name = "notify",defaultValue="0") var notify:Int,
    @ColumnInfo(name = "notify_type",defaultValue="none") var notifyType:String,
    @ColumnInfo(name = "notify_every",defaultValue="0") var notifyEvery:Int,
    @ColumnInfo(name = "notify_every_type",defaultValue="none") var notifyEveryType:String,
    @ColumnInfo(name = "item_status",defaultValue="0") var itemStatus:Int,//0 active,1=deleted,2=permanently deleted
    @ColumnInfo(name = "uploaded",defaultValue="0") var uploaded:Int //0=not yet uploaded,1=uploaded
){
    companion object{
        const val NOT_DELETED_STATUS = 0
        const val DELETED_STATUS = 1
        const val NOT_UPLOADED = 0
        const val UPLOADED = 1
        const val NOT_RECURRING = 0
        const val RECURRING = 1
    }
}