package com.example.allhome.recipes.viewmodel

import android.content.Context
import androidx.lifecycle.ViewModel
import com.example.allhome.data.AllHomeDatabase
import com.example.allhome.data.entities.*
import kotlinx.coroutines.CoroutineName
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers

class RecipesFragmentViewModel:ViewModel() {
    val mCoroutineScope = CoroutineScope(Dispatchers.IO + CoroutineName("RecipesFragmentViewModel"))

    var mFiltering = false

    var mCostSpinnerSelectedFilter: String = ""
    var mServingSelectedFilter: String = ""
    var mPrepPlusCookTimeSelectedFilter: String= ""

    var mCostString: String = ""
    var mServingString: String = ""
    var mPrepPlusCookHourString: String = ""
    var mPrepPlusCookMinutesString: String = ""

    var mHasCostInput:Boolean = false
    var mHasServingInput:Boolean = false
    var mHasHourOrMinuteInput:Boolean = false

    suspend fun getRecipes(context: Context): List<RecipeEntity> {
        return AllHomeDatabase.getDatabase(context).getRecipeDAO().getRecipes()
    }
    suspend fun getIngredients(context:Context,recipeUniqueId:String):List<IngredientEntity>{
        return AllHomeDatabase.getDatabase(context).getIngredientDAO().getIngredientsByRecipeUniqueId(recipeUniqueId)
    }

    suspend fun getIngredientsForTransferringInGroceryList(context:Context,recipeUniqueId:String):List<IngredientEntityTransferringToGroceryList>{
        return AllHomeDatabase.getDatabase(context).getIngredientDAO().getIngredientsForGroceryListByRecipeUniqueId(recipeUniqueId)
    }

    suspend fun getSteps(context:Context,recipeUniqueId:String):List<RecipeStepEntity>{
        return AllHomeDatabase.getDatabase(context).getRecipeStepDAO().getStepsByRecipeUniqueId(recipeUniqueId)
    }

    suspend fun deleteRecipe(context:Context,recipeUniqueId:String){
        val recipeDAO = AllHomeDatabase.getDatabase(context).getRecipeDAO()
        val recipeStepDAO = AllHomeDatabase.getDatabase(context).getRecipeStepDAO()
        val ingredientDAO = AllHomeDatabase.getDatabase(context).getIngredientDAO()

        recipeDAO.updateRecipeByUniqueIdAsDeleted(recipeUniqueId)
        recipeStepDAO.updateStepsByRecipeUniqueIdAsDeleted(recipeUniqueId)
        ingredientDAO.updateIngredientByRecipeUniqueIdAsDeleted(recipeUniqueId)
    }
    suspend fun getItemByGroceryListAutoGeneratedIDnameAndUnit(context:Context,groceryListAutoGeneratedId:String,name:String,unit:String):GroceryItemEntity?{

        return AllHomeDatabase.getDatabase(context).groceryItemDAO().getItemByGroceryListAutoGeneratedIDnameAndUnit(groceryListAutoGeneratedId,name,unit)

    }
    suspend fun addGroceryListItem(context:Context,groceryItemEntity:GroceryItemEntity){
        AllHomeDatabase.getDatabase(context).groceryItemDAO().addItem(groceryItemEntity)
    }

    suspend fun updateItemQuantityDatetimeModified(context: Context,quantity:Double,id:Int,datetimeModified:String):Int{
       return AllHomeDatabase.getDatabase(context).groceryItemDAO().updateItemQuantityDatetimeModified(quantity,id,datetimeModified)

    }

    suspend fun filterByCostServingAndTotalPrepAndCookTime(context:Context,cost:Double,serving:Int,totalPrepAndCookTimeInMinutes:Int){

    }
}

