package com.example.allhome.grocerylist.viewmodel

import android.content.Context
import androidx.lifecycle.ViewModel
import com.example.allhome.data.AllHomeDatabase
import com.example.allhome.data.entities.GroceryListEntity
import com.example.allhome.data.entities.GroceryListWithItemCount
import kotlinx.coroutines.CoroutineName
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers

class ArchivedGroceryListInformationActivityViewModel: ViewModel() {

    val coroutineScope = CoroutineScope(Dispatchers.IO + CoroutineName("GroceryListInformationActivityViewModel"))
    lateinit var mGroceryListWithItemCount:GroceryListWithItemCount

    suspend fun getGroceryListItem(context: Context, autoGeneratedUniqueId:String) : GroceryListWithItemCount {

           return  AllHomeDatabase.getDatabase(context).groceryListDAO().getGroceryListWithItemCount(autoGeneratedUniqueId)

    }


    suspend fun updateGroceryList(context:Context,name:String,scheduleDateTime:String,location:String,longitude:Double,latitude:Double, autoGeneratedUniqueId:String){
        AllHomeDatabase.getDatabase(context).groceryListDAO().updateGroceryList(name,scheduleDateTime,location,longitude,latitude,autoGeneratedUniqueId)
    }

    suspend fun updateGroceryList(context:Context,groceryListEntity: GroceryListEntity):Int{
        val count = AllHomeDatabase.getDatabase(context).groceryListDAO().updateGroceryList(groceryListEntity)
        return count
    }




}

