package com.example.allhome.grocerylist.trash_grocery_list

import android.content.Intent
import android.os.Bundle
import android.view.*
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.widget.PopupMenu
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProvider
import androidx.recyclerview.widget.RecyclerView
import com.example.allhome.R
import com.example.allhome.data.entities.GroceryListEntityValues
import com.example.allhome.data.entities.GroceryListWithItemCount
import com.example.allhome.databinding.FragmentTrashGroceryListBinding
import com.example.allhome.databinding.TrashGroceryListItemBinding
import com.example.allhome.grocerylist.*
import com.example.allhome.grocerylist.viewmodel.TrashGroceryListFragmentViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.text.SimpleDateFormat
import java.util.*


class TrashGroceryListFragment : Fragment() {



    private lateinit var mDataBindingUtil: FragmentTrashGroceryListBinding
    private lateinit var mGroceryListFragmentViewModel: TrashGroceryListFragmentViewModel;

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setHasOptionsMenu(true)
        requireActivity().title = "Trash Grocery List"


    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        // Inflate the layout for this fragment


        mGroceryListFragmentViewModel = ViewModelProvider(this).get(TrashGroceryListFragmentViewModel::class.java)
        mDataBindingUtil = DataBindingUtil.inflate(inflater, R.layout.fragment_trash_grocery_list, container, false)
        mDataBindingUtil.apply {

        }

        val groceryListRecyclerViewAdapter = TrashGroceryListRecyclerViewAdapter(this, mGroceryListFragmentViewModel)
        mDataBindingUtil.trashGroceryListRecyclerview.adapter = groceryListRecyclerViewAdapter

        mGroceryListFragmentViewModel.coroutineScope.launch {
            mGroceryListFragmentViewModel.getDeletedGroceryLists(requireContext())
            withContext(Dispatchers.Main) {
                groceryListRecyclerViewAdapter.mGroceryListWithItemCount = mGroceryListFragmentViewModel.groceryLists
                groceryListRecyclerViewAdapter.notifyDataSetChanged()
            }

        }


        return mDataBindingUtil.root
    }

    override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
        //super.onCreateOptionsMenu(menu, inflater)
        inflater.inflate(R.menu.grocery_list_menu,menu)
    }


}

/**
 *
 */
class TrashGroceryListRecyclerViewAdapter(val trashGroceryListFragment: TrashGroceryListFragment, val trashGroceryListFragmentViewModel: TrashGroceryListFragmentViewModel) : RecyclerView.Adapter<TrashGroceryListRecyclerViewAdapter.ItemViewHolder>() {
    var mGroceryListWithItemCount: List<GroceryListWithItemCount> = arrayListOf()


    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ItemViewHolder {

        val layoutInflater = LayoutInflater.from(parent.context)



        val groceryListItemBinding = TrashGroceryListItemBinding.inflate(layoutInflater, parent, false)
        val itemViewHolder = ItemViewHolder(groceryListItemBinding)

        return itemViewHolder;

    }

    override fun onBindViewHolder(holder: ItemViewHolder, position: Int) {

        val groceryItemEntity = mGroceryListWithItemCount[position]
        holder.groceryListItemBinding.groceryListWithCount= groceryItemEntity
        holder.groceryListItemBinding.executePendingBindings()
    }

    override fun getItemCount(): Int {
        return mGroceryListWithItemCount.size
    }

    /**
     *
     */
    inner  class ItemViewHolder(var groceryListItemBinding: TrashGroceryListItemBinding) : RecyclerView.ViewHolder(groceryListItemBinding.root), View.OnClickListener {

        init{
            groceryListItemBinding.root.setOnClickListener(this)
            groceryListItemBinding.moreActionImageView.setOnClickListener(this)
            groceryListItemBinding.itemCountAndBoughtTextView.setOnClickListener(this)
        }

        override fun onClick(view: View?) {

            if(view?.id == R.id.trash_grocery_item_list_parent_layout){
                Toast.makeText(view!!.context,"Parent toast",Toast.LENGTH_SHORT).show()

                val groceryListWithCount  = groceryListItemBinding.groceryListWithCount
                val intent = Intent(trashGroceryListFragment.requireContext(), TrashSingleGroceryListActivity::class.java)
                intent.putExtra(AddGroceryListItemActivity.GROCERY_LIST_UNIQUE_ID_EXTRA_DATA_TAG, groceryListWithCount?.groceryListEntity?.autoGeneratedUniqueId)
                trashGroceryListFragment.startActivityForResult(intent, GroceryListFragment.OPEN_SINGLE_GROCERY_LIST_REQUEST)
            }else if(view?.id == R.id.itemCountAndBoughtTextView || view?.id == R.id.moreActionImageView){

                val popupMenu = PopupMenu(trashGroceryListFragment.requireContext(), groceryListItemBinding.moreActionImageView)
                popupMenu.menuInflater.inflate(R.menu.trash_grocery_list_action, popupMenu.menu)
                popupMenu.setOnMenuItemClickListener(PopupMenu.OnMenuItemClickListener {

                    when (it.itemId) {
                        R.id.trash_grocery_list_restore_menu -> {



                        }
                        R.id.trash_grocery_list_create_copy_menu -> {

                            val groceryListNameInputDialog = GroceryListFragment.CustomDialog(trashGroceryListFragment.requireContext())
                            groceryListNameInputDialog.setGroceryListName("- copy")
                            groceryListNameInputDialog.setButtonClickListener(View.OnClickListener {

                            })
                            groceryListNameInputDialog.createPositiveButton("Continue")
                            groceryListNameInputDialog.show()

                        }
                        R.id.trash_grocery_list_delete_permanently_menu -> {





                        }
                    }
                    true
                })
                popupMenu.show()
            }



        }


    }

}
